FROM yufree/xcms:latest
MAINTAINER "Miao Yu" yufreecas@gmail.com
RUN apt-get update \
  && installGithub.r \
    omegahat/XMLSchema \
    cran/SSOAP \
    nathaniel-mahieu/warpgroup \
    yufree/mz.unity \
    cbroeckl/RAMClustR \
    cran/ChemometricsWithR \
    rwehrens/BatchCorrMetabolomics \
    yufree/decoMS2 \
    KechrisLab/MSPrep \
    yufree/MetDIA \
    WMBEdmands/MetMSLine \
    WMBEdmands/compMS2Miner \
    c-ruttkies/MetFragR/metfRag \
    ropensci/rfigshare \
    Aurametrix/R/GRAPH/MetabNet \
    kuppal2/xMWAS \
    yufree/apLCMS \
    yufree/xMSanalyzer \
    yufree/xMSannotator \
    yufree/x13cms \
    yufree/enviGCMS \
    yufree/pmd \
    