FROM yufree/xcms:small
MAINTAINER "Miao Yu" yufreecas@gmail.com

RUN apt-get update \
  && installGithub.r \
    omegahat/XMLSchema \
    cran/SSOAP \
    xia-lab/MetaboAnalystR \
    yufree/apLCMS \
    yufree/xMSanalyzer \
    yufree/xMSannotator \
    yufree/x13cms \
    yufree/pmd \
    nathaniel-mahieu/warpgroup \
    nathaniel-mahieu/mz.unity \
    pattilab/credential \
    cbroeckl/RAMClustR \
    rwehrens/BatchCorrMetabolomics \
    yufree/decoMS2 \
    
